CREATE TABLE coin_price(
`num` INT(11) NOT NULL AUTO_INCREMENT,
`exchange` VARCHAR(50) NOT NULL,
`name` VARCHAR(100) NOT NULL,
`date` INT(11) NOT NULL,
`opening` DOUBLE NOT NULL,
`closing` DOUBLE NOT NULL,
PRIMARY KEY(`num`) USING BTREE 
)